obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.2399, -0.051], [-0.2399, -0.051], [-0.2399, 0.051], [0.2399, 0.051]]
inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}